variables:
  apps:
    - one
    - two
    - three
  bigstring: "This is bigger"
  moomoo: "got it"

templates:
  - src: tests/template1.jinja2
    dst: tests/template1.out


collect:
  - regex: dc-\d{2}.+\.orig\.tpl
    dst: tests/combined.yaml

  - regex: dc-\d{2}.+\.orig\.tpl
    dst: tests/combinedv2.yaml
    indent: 2
    preamble: |
      version: '2'
      services:
    postamble: |
      networks:
        front-tier:
          driver: bridge
        back-tier:
          driver: bridge